# Generated by Django 5.2.17 on 2026-09-23 22:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(db_index=True, max_length=64)),
                ('nazwa', models.CharField(max_length=800)),
                ('combi', models.CharField(db_index=True, max_length=900)),
                ('cena_det', models.DecimalField(decimal_places=2, max_digits=12)),
                ('zdjecie', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['combi'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klient', models.CharField(blank=True, default='Propozycja', max_length=200)),
                ('created_on', models.DateField()),
                ('valid_days', models.PositiveIntegerField(default=14)),
                ('with_photos', models.BooleanField(default=True)),
                ('show_codes', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OfferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('combi', models.CharField(blank=True, max_length=900)),
                ('rabat', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6)),
                ('ilosc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='offers.offer')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
